var $header = $('header');
var $h1 = $('h1');
var $main = $('main');
var $p1 = $('main p:first-child');
var $h2 = $('h2');
var $li = $('main li');
var $img = $('img');
var $li1 = $('li:first-child');
var $li2 = $('li:last-child');
var $dl = $('dl');
var $dt = $('dt');
	$header.addClass('masthead');
	$h1.removeClass('big-heading').addClass('logo');
	$main.addClass('wrapper');
	$p1.addClass('intro');
	$h2.addClass('slug-head');
	$li.addClass('slug-list');
	$img.addClass('slug-img');
	$li1.addClass('slug-list-first');
	$li2.addClass('slug-list-last');
	$dl.addClass('classification');
	$dt.removeClass('big-label');
	$li2.show();
